// <auto-generated />
using System;
using AspNetCoreSpa.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreSpa.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190620190209_Populate_Country")]
    partial class Populate_Country
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreSpa.Domain.Enities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("RegioneCode")
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2def92d2-fff9-419c-ab65-d6aae8a04c26"),
                            Name = "Afghanistan",
                            RegioneCode = "AFG"
                        },
                        new
                        {
                            Id = new Guid("80338b82-972c-4ea2-bae9-6656107a1202"),
                            Name = "Åland Islands",
                            RegioneCode = "ALA"
                        },
                        new
                        {
                            Id = new Guid("4a556545-16a4-4414-90e1-5a2ee2847d77"),
                            Name = "Albania",
                            RegioneCode = "ALB"
                        },
                        new
                        {
                            Id = new Guid("f39873ac-b41d-466a-a6c5-b1bf03910f17"),
                            Name = "Algeria",
                            RegioneCode = "DZA"
                        },
                        new
                        {
                            Id = new Guid("0e89af10-978e-443e-9de0-f498543e533e"),
                            Name = "American Samoa",
                            RegioneCode = "ASM"
                        },
                        new
                        {
                            Id = new Guid("06df6c08-cea7-441c-91b4-6cd55d81f4cd"),
                            Name = "Andorra",
                            RegioneCode = "AND"
                        },
                        new
                        {
                            Id = new Guid("24bbf0bf-f5e1-4944-90fb-1f17f0aa5ba9"),
                            Name = "Angola",
                            RegioneCode = "AGO"
                        },
                        new
                        {
                            Id = new Guid("ac6b2eb9-8061-45da-a938-3809cf81918e"),
                            Name = "Anguilla",
                            RegioneCode = "AIA"
                        },
                        new
                        {
                            Id = new Guid("2e0eef48-9c21-431b-a387-e5b18ff1458f"),
                            Name = "Antarctica",
                            RegioneCode = "ATA"
                        },
                        new
                        {
                            Id = new Guid("683b32c5-b003-4ad4-9115-8b0e11d8eebe"),
                            Name = "Antigua and Barbuda",
                            RegioneCode = "ATG"
                        },
                        new
                        {
                            Id = new Guid("58ed9a0d-0648-4138-a64a-f54b4091720c"),
                            Name = "Argentina",
                            RegioneCode = "ARG"
                        },
                        new
                        {
                            Id = new Guid("d531bc17-0c16-4233-9eac-5fd7984448d8"),
                            Name = "Armenia",
                            RegioneCode = "ARM"
                        },
                        new
                        {
                            Id = new Guid("688ddb6a-c8e9-4902-8573-a4b91bbe7741"),
                            Name = "Aruba",
                            RegioneCode = "ABW"
                        },
                        new
                        {
                            Id = new Guid("bbbbe4c1-3a70-44ee-9669-a68b811f8418"),
                            Name = "Australia",
                            RegioneCode = "AUS"
                        },
                        new
                        {
                            Id = new Guid("9e2f96d7-e472-4ed9-961f-14013bffed55"),
                            Name = "Austria",
                            RegioneCode = "AUT"
                        },
                        new
                        {
                            Id = new Guid("1cbb91a4-a0f5-4cdb-be86-9bfd1fadadc3"),
                            Name = "Azerbaijan",
                            RegioneCode = "AZE"
                        },
                        new
                        {
                            Id = new Guid("00867684-e79d-44b6-990f-f70e6c53baf5"),
                            Name = "Bahamas",
                            RegioneCode = "BHS"
                        },
                        new
                        {
                            Id = new Guid("5637d6bc-0f9e-44fa-9208-8263354943f2"),
                            Name = "Bahrain",
                            RegioneCode = "BHR"
                        },
                        new
                        {
                            Id = new Guid("bb59f368-8a5e-41ff-812a-d2f316c17b58"),
                            Name = "Bangladesh",
                            RegioneCode = "BGD"
                        },
                        new
                        {
                            Id = new Guid("a5f2dd71-a903-4110-a6b6-2df6d16d50cd"),
                            Name = "Barbados",
                            RegioneCode = "BRB"
                        },
                        new
                        {
                            Id = new Guid("c0711155-b598-407a-91c4-86310bc239d7"),
                            Name = "Belarus",
                            RegioneCode = "BLR"
                        },
                        new
                        {
                            Id = new Guid("50555b0f-d488-499f-b8b2-7cde84e57fc7"),
                            Name = "Belgium",
                            RegioneCode = "BEL"
                        },
                        new
                        {
                            Id = new Guid("ebe36781-d6e2-42b7-be85-4e9560d86326"),
                            Name = "Belize",
                            RegioneCode = "BLZ"
                        },
                        new
                        {
                            Id = new Guid("219018b7-0710-4d3c-a7b4-ccf7f82e4e42"),
                            Name = "Benin",
                            RegioneCode = "BEN"
                        },
                        new
                        {
                            Id = new Guid("13071079-48b5-40a9-9fa4-5dfac572dca4"),
                            Name = "Bermuda",
                            RegioneCode = "BMU"
                        },
                        new
                        {
                            Id = new Guid("e051e72f-7539-4e60-bfe8-f7409b8fe158"),
                            Name = "Bhutan",
                            RegioneCode = "BTN"
                        },
                        new
                        {
                            Id = new Guid("3084983e-ce03-4255-a715-6e6998519ebc"),
                            Name = "Bolivia (Plurinational State of)",
                            RegioneCode = "BOL"
                        },
                        new
                        {
                            Id = new Guid("7f33ff02-3975-4b9b-a899-9503e815d581"),
                            Name = "Bonaire, Sint Eustatius and Saba",
                            RegioneCode = "BES"
                        },
                        new
                        {
                            Id = new Guid("7543fa8e-b16b-4476-bc8f-7becb815cf17"),
                            Name = "Bosnia and Herzegovina",
                            RegioneCode = "BIH"
                        },
                        new
                        {
                            Id = new Guid("597c64ff-7d44-44b8-95ce-2afc6ce4acc8"),
                            Name = "Botswana",
                            RegioneCode = "BWA"
                        },
                        new
                        {
                            Id = new Guid("28b1aa8e-e337-45b0-a18d-e3edbf2ab3c4"),
                            Name = "Bouvet Island",
                            RegioneCode = "BVT"
                        },
                        new
                        {
                            Id = new Guid("6d73d59d-f354-4e54-810c-5d1a0dda961b"),
                            Name = "Brazil",
                            RegioneCode = "BRA"
                        },
                        new
                        {
                            Id = new Guid("2689acd3-3894-4cb4-ba72-b7c7d505f955"),
                            Name = "British Indian Ocean Territory",
                            RegioneCode = "IOT"
                        },
                        new
                        {
                            Id = new Guid("0ee077fe-41de-460e-bf23-807a0d8168ae"),
                            Name = "Brunei Darussalam",
                            RegioneCode = "BRN"
                        },
                        new
                        {
                            Id = new Guid("6fd47f87-2550-4f34-a265-e93cf791485e"),
                            Name = "Bulgaria",
                            RegioneCode = "BGR"
                        },
                        new
                        {
                            Id = new Guid("e19c097b-d7a4-4201-b239-767264c75104"),
                            Name = "Burkina Faso",
                            RegioneCode = "BFA"
                        },
                        new
                        {
                            Id = new Guid("a42f3752-d76a-41ea-a6e9-cdf41dc3343b"),
                            Name = "Burundi",
                            RegioneCode = "BDI"
                        },
                        new
                        {
                            Id = new Guid("6ac45f00-68ae-4c32-82b0-b21a0c173abf"),
                            Name = "Cabo Verde",
                            RegioneCode = "CPV"
                        },
                        new
                        {
                            Id = new Guid("b60bc2be-5dae-4284-a300-f5026e83616a"),
                            Name = "Cambodia",
                            RegioneCode = "KHM"
                        },
                        new
                        {
                            Id = new Guid("69c588f5-aa7c-4926-96d8-22da7f5767ad"),
                            Name = "Cameroon",
                            RegioneCode = "CMR"
                        },
                        new
                        {
                            Id = new Guid("a97fa95d-7cb6-4f49-bf15-de959b807978"),
                            Name = "Canada",
                            RegioneCode = "CAN"
                        },
                        new
                        {
                            Id = new Guid("6c85b1ab-fb12-4441-b9d6-7d5a3574d4ad"),
                            Name = "Cayman Islands",
                            RegioneCode = "CYM"
                        },
                        new
                        {
                            Id = new Guid("87204e73-b151-42f2-b860-74de3a3dce24"),
                            Name = "Central African Republic",
                            RegioneCode = "CAF"
                        },
                        new
                        {
                            Id = new Guid("87399cf5-6683-46d9-908f-1e85293beb15"),
                            Name = "Chad",
                            RegioneCode = "TCD"
                        },
                        new
                        {
                            Id = new Guid("7be61c14-2f77-4d99-9035-f87933c6269b"),
                            Name = "Chile",
                            RegioneCode = "CHL"
                        },
                        new
                        {
                            Id = new Guid("2cd1226c-3af5-4ab8-a1d1-69eb9cce77d2"),
                            Name = "China",
                            RegioneCode = "CHN"
                        },
                        new
                        {
                            Id = new Guid("52738049-028c-4059-aa1f-910d405d0891"),
                            Name = "Christmas Island",
                            RegioneCode = "CXR"
                        },
                        new
                        {
                            Id = new Guid("4d8f296a-9c4b-4344-8bf9-dcde821988ea"),
                            Name = "Cocos (Keeling) Islands",
                            RegioneCode = "CCK"
                        },
                        new
                        {
                            Id = new Guid("43a15750-ca95-4f6e-861f-bf1bf42649f6"),
                            Name = "Colombia",
                            RegioneCode = "COL"
                        },
                        new
                        {
                            Id = new Guid("0ac03e09-8332-47a2-b3e9-1960c830e0d4"),
                            Name = "Comoros",
                            RegioneCode = "COM"
                        },
                        new
                        {
                            Id = new Guid("a0bb5f6e-ce20-44dc-a5a4-e8ac6abc6600"),
                            Name = "Congo",
                            RegioneCode = "COG"
                        },
                        new
                        {
                            Id = new Guid("bb8c173c-2a90-41d1-8434-120319577e84"),
                            Name = "Congo, Democratic Republic of the",
                            RegioneCode = "COD"
                        },
                        new
                        {
                            Id = new Guid("e954cfdb-cc6b-4cb0-8c15-7d601ae16f76"),
                            Name = "Cook Islands",
                            RegioneCode = "COK"
                        },
                        new
                        {
                            Id = new Guid("78245d1e-4afa-456c-a04d-d08933237823"),
                            Name = "Costa Rica",
                            RegioneCode = "CRI"
                        },
                        new
                        {
                            Id = new Guid("12d3223f-7543-4932-96a2-808dddd1acf0"),
                            Name = "Côte d'Ivoire",
                            RegioneCode = "CIV"
                        },
                        new
                        {
                            Id = new Guid("7ec787ba-ab76-44f0-8f9f-a12f67cc81d0"),
                            Name = "Croatia",
                            RegioneCode = "HRV"
                        },
                        new
                        {
                            Id = new Guid("0fb25f41-e9f6-4b86-8f8f-4d54af348ead"),
                            Name = "Cuba",
                            RegioneCode = "CUB"
                        },
                        new
                        {
                            Id = new Guid("ed304576-0848-42dc-861b-f48a3614bb73"),
                            Name = "Curaçao",
                            RegioneCode = "CUW"
                        },
                        new
                        {
                            Id = new Guid("2146c53f-c8b4-46d6-bc34-f92b9cbd99f9"),
                            Name = "Cyprus",
                            RegioneCode = "CYP"
                        },
                        new
                        {
                            Id = new Guid("409a2699-165f-4a72-adc4-de26edfeee89"),
                            Name = "Czechia",
                            RegioneCode = "CZE"
                        },
                        new
                        {
                            Id = new Guid("6704cf6d-49a4-4dd8-9e14-c5fe97d32120"),
                            Name = "Denmark",
                            RegioneCode = "DNK"
                        },
                        new
                        {
                            Id = new Guid("871b69e3-0d94-4e3e-a486-928c73f36972"),
                            Name = "Djibouti",
                            RegioneCode = "DJI"
                        },
                        new
                        {
                            Id = new Guid("b15ceebe-81b3-4657-9150-62551829949f"),
                            Name = "Dominica",
                            RegioneCode = "DMA"
                        },
                        new
                        {
                            Id = new Guid("35ae1ae8-f07f-4ca0-aeff-157252f4d4fe"),
                            Name = "Dominican Republic",
                            RegioneCode = "DOM"
                        },
                        new
                        {
                            Id = new Guid("15f9ccf7-dbda-47cb-95aa-55135a888c36"),
                            Name = "Ecuador",
                            RegioneCode = "ECU"
                        },
                        new
                        {
                            Id = new Guid("52f61d46-bf77-494c-a05d-33e0abf29a0f"),
                            Name = "Egypt",
                            RegioneCode = "EGY"
                        },
                        new
                        {
                            Id = new Guid("bf896bc0-305a-402c-a940-67e430834fa0"),
                            Name = "El Salvador",
                            RegioneCode = "SLV"
                        },
                        new
                        {
                            Id = new Guid("4b641190-3d6a-4eee-9f06-d5ce825a6d36"),
                            Name = "Equatorial Guinea",
                            RegioneCode = "GNQ"
                        },
                        new
                        {
                            Id = new Guid("68432341-8ec9-4b2e-84b0-34725f5cbe28"),
                            Name = "Eritrea",
                            RegioneCode = "ERI"
                        },
                        new
                        {
                            Id = new Guid("159a79fc-f215-4181-b25e-3bf8133b11a0"),
                            Name = "Estonia",
                            RegioneCode = "EST"
                        },
                        new
                        {
                            Id = new Guid("ca877833-6b7a-400c-b975-5b451e3b7acb"),
                            Name = "Eswatini",
                            RegioneCode = "SWZ"
                        },
                        new
                        {
                            Id = new Guid("9ff8ede6-6161-4923-85ae-a4cc71cf6772"),
                            Name = "Ethiopia",
                            RegioneCode = "ETH"
                        },
                        new
                        {
                            Id = new Guid("fea72906-c869-45fa-9126-b87d8873614d"),
                            Name = "Falkland Islands (Malvinas)",
                            RegioneCode = "FLK"
                        },
                        new
                        {
                            Id = new Guid("56ffbb40-1097-421c-bd84-3f1ce141ec4b"),
                            Name = "Faroe Islands",
                            RegioneCode = "FRO"
                        },
                        new
                        {
                            Id = new Guid("b6c00c67-6a10-471d-aaa5-7e4badf2568e"),
                            Name = "Fiji",
                            RegioneCode = "FJI"
                        },
                        new
                        {
                            Id = new Guid("7cbc558b-ead5-41da-9a95-180b2ecd3379"),
                            Name = "Finland",
                            RegioneCode = "FIN"
                        },
                        new
                        {
                            Id = new Guid("c556a75f-7186-4a4c-a21b-c5a264633df3"),
                            Name = "France",
                            RegioneCode = "FRA"
                        },
                        new
                        {
                            Id = new Guid("49dc8a79-12bc-4efe-ac71-9186e711afd5"),
                            Name = "French Guiana",
                            RegioneCode = "GUF"
                        },
                        new
                        {
                            Id = new Guid("cd48f169-746a-47e4-ab99-901a5f1397f4"),
                            Name = "French Polynesia",
                            RegioneCode = "PYF"
                        },
                        new
                        {
                            Id = new Guid("bf29d02c-2eb7-4af8-b5ae-6621e55bbba2"),
                            Name = "French Southern Territories",
                            RegioneCode = "ATF"
                        },
                        new
                        {
                            Id = new Guid("10cf0be8-bca8-4430-80d7-ec3851b2ad19"),
                            Name = "Gabon",
                            RegioneCode = "GAB"
                        },
                        new
                        {
                            Id = new Guid("438ee27e-f6b6-4d57-8e9f-72ec4b5d52c0"),
                            Name = "Gambia",
                            RegioneCode = "GMB"
                        },
                        new
                        {
                            Id = new Guid("4d715b5a-a39a-45cb-a2aa-babe741a7158"),
                            Name = "Georgia",
                            RegioneCode = "GEO"
                        },
                        new
                        {
                            Id = new Guid("d74bace3-2dfa-4ba1-8d22-4956939c442b"),
                            Name = "Germany",
                            RegioneCode = "DEU"
                        },
                        new
                        {
                            Id = new Guid("c0030b32-cbfc-4d8f-bde1-00ebc6fdcac6"),
                            Name = "Ghana",
                            RegioneCode = "GHA"
                        },
                        new
                        {
                            Id = new Guid("ba209907-281e-446a-a97a-9303e0e4030b"),
                            Name = "Gibraltar",
                            RegioneCode = "GIB"
                        },
                        new
                        {
                            Id = new Guid("5cbdf134-408e-4c0e-bc4b-5698f58a0be0"),
                            Name = "Greece",
                            RegioneCode = "GRC"
                        },
                        new
                        {
                            Id = new Guid("2f95f5ff-3d15-45a3-8a87-91ff768d9ecb"),
                            Name = "Greenland",
                            RegioneCode = "GRL"
                        },
                        new
                        {
                            Id = new Guid("3eb44ca7-f491-4e23-b8e9-0225b492cfde"),
                            Name = "Grenada",
                            RegioneCode = "GRD"
                        },
                        new
                        {
                            Id = new Guid("68235833-d0c2-42e1-bc52-544c75ff25ab"),
                            Name = "Guadeloupe",
                            RegioneCode = "GLP"
                        },
                        new
                        {
                            Id = new Guid("0bac8afd-e9d4-498f-be13-42f623290cfb"),
                            Name = "Guam",
                            RegioneCode = "GUM"
                        },
                        new
                        {
                            Id = new Guid("edcbbafd-8a87-4c77-8fbd-2e952a2da7ac"),
                            Name = "Guatemala",
                            RegioneCode = "GTM"
                        },
                        new
                        {
                            Id = new Guid("fa260694-c3ab-4bb2-9033-5104b196ac9d"),
                            Name = "Guernsey",
                            RegioneCode = "GGY"
                        },
                        new
                        {
                            Id = new Guid("ab6280e7-229e-4191-aded-e829e96d2602"),
                            Name = "Guinea",
                            RegioneCode = "GIN"
                        },
                        new
                        {
                            Id = new Guid("b384155f-7d7e-430b-b367-76c4126d7186"),
                            Name = "Guinea-Bissau",
                            RegioneCode = "GNB"
                        },
                        new
                        {
                            Id = new Guid("0e52dc84-af44-46f7-aea0-9e0b597a2cd3"),
                            Name = "Guyana",
                            RegioneCode = "GUY"
                        },
                        new
                        {
                            Id = new Guid("c0a2ef8a-c1a8-4c34-aa16-7744df5ca399"),
                            Name = "Haiti",
                            RegioneCode = "HTI"
                        },
                        new
                        {
                            Id = new Guid("485d8a42-a7eb-4ad8-a1d4-c7196d265d38"),
                            Name = "Heard Island and McDonald Islands",
                            RegioneCode = "HMD"
                        },
                        new
                        {
                            Id = new Guid("276c19f3-230f-4c19-b817-0db872e9af2a"),
                            Name = "Holy See",
                            RegioneCode = "VAT"
                        },
                        new
                        {
                            Id = new Guid("81f619fa-72b0-436f-b62b-569ead37acbc"),
                            Name = "Honduras",
                            RegioneCode = "HND"
                        },
                        new
                        {
                            Id = new Guid("5bd51888-9274-4e5b-a12b-9effaf0b19a0"),
                            Name = "Hong Kong",
                            RegioneCode = "HKG"
                        },
                        new
                        {
                            Id = new Guid("ac479611-5f2c-4a1c-ac86-103027585d22"),
                            Name = "Hungary",
                            RegioneCode = "HUN"
                        },
                        new
                        {
                            Id = new Guid("fba4a763-335b-4565-aa83-f40e769fa037"),
                            Name = "Iceland",
                            RegioneCode = "ISL"
                        },
                        new
                        {
                            Id = new Guid("d2af06aa-f830-4eff-b74a-5d43201c2fc3"),
                            Name = "India",
                            RegioneCode = "IND"
                        },
                        new
                        {
                            Id = new Guid("904c67ee-8938-43d3-9cf1-a08fe66558ad"),
                            Name = "Indonesia",
                            RegioneCode = "IDN"
                        },
                        new
                        {
                            Id = new Guid("af93b424-922b-4c9e-beeb-18a2566ca5b7"),
                            Name = "Iran (Islamic Republic of)",
                            RegioneCode = "IRN"
                        },
                        new
                        {
                            Id = new Guid("b6cdfc5f-6618-4bab-954c-fbd11879ff03"),
                            Name = "Iraq",
                            RegioneCode = "IRQ"
                        },
                        new
                        {
                            Id = new Guid("32bf1e47-7690-4c30-a9b3-4bdb11a55513"),
                            Name = "Ireland",
                            RegioneCode = "IRL"
                        },
                        new
                        {
                            Id = new Guid("4973db54-5e64-4a13-8d15-cd6f23a848ba"),
                            Name = "Isle of Man",
                            RegioneCode = "IMN"
                        },
                        new
                        {
                            Id = new Guid("b8662c14-c6ec-4cc8-9635-e9a907e9d2dc"),
                            Name = "Israel",
                            RegioneCode = "ISR"
                        },
                        new
                        {
                            Id = new Guid("18beeda3-36ff-437f-ab66-04199c324a63"),
                            Name = "Italy",
                            RegioneCode = "ITA"
                        },
                        new
                        {
                            Id = new Guid("b787c80f-b034-40af-ae6a-8981557293cc"),
                            Name = "Jamaica",
                            RegioneCode = "JAM"
                        },
                        new
                        {
                            Id = new Guid("eed6efdf-fedd-460a-bb46-d23c1b23e9fc"),
                            Name = "Japan",
                            RegioneCode = "JPN"
                        },
                        new
                        {
                            Id = new Guid("ed29c6ab-a272-43eb-aa91-f256f6765287"),
                            Name = "Jersey",
                            RegioneCode = "JEY"
                        },
                        new
                        {
                            Id = new Guid("8c8658e0-f841-47cd-9672-6481854b959b"),
                            Name = "Jordan",
                            RegioneCode = "JOR"
                        },
                        new
                        {
                            Id = new Guid("435aef1a-075c-4105-acd0-7e6b0ff0d824"),
                            Name = "Kazakhstan",
                            RegioneCode = "KAZ"
                        },
                        new
                        {
                            Id = new Guid("4a5d51dd-5f1b-448c-a84d-b0ae8208c6ae"),
                            Name = "Kenya",
                            RegioneCode = "KEN"
                        },
                        new
                        {
                            Id = new Guid("330c51e7-8463-4493-a33d-96db7916f72f"),
                            Name = "Kiribati",
                            RegioneCode = "KIR"
                        },
                        new
                        {
                            Id = new Guid("0dc20b4f-fe29-4ccd-893d-0a02f7c4b275"),
                            Name = "Korea (Democratic People's Republic of)",
                            RegioneCode = "PRK"
                        },
                        new
                        {
                            Id = new Guid("5652e664-3cf2-4149-b1fd-b65e21f6b703"),
                            Name = "Korea, Republic of",
                            RegioneCode = "KOR"
                        },
                        new
                        {
                            Id = new Guid("b833970a-f3fc-479f-847f-c22bd126865c"),
                            Name = "Kuwait",
                            RegioneCode = "KWT"
                        },
                        new
                        {
                            Id = new Guid("d42facde-95ae-4e2d-84e7-23b60aafe2b3"),
                            Name = "Kyrgyzstan",
                            RegioneCode = "KGZ"
                        },
                        new
                        {
                            Id = new Guid("d4b39e27-94a9-470b-840f-cb5c3dd21533"),
                            Name = "Lao People's Democratic Republic",
                            RegioneCode = "LAO"
                        },
                        new
                        {
                            Id = new Guid("209db596-175f-461f-930d-d68b662fcd7b"),
                            Name = "Latvia",
                            RegioneCode = "LVA"
                        },
                        new
                        {
                            Id = new Guid("b41d287a-20f7-4c31-8f84-e9aaa24139f5"),
                            Name = "Lebanon",
                            RegioneCode = "LBN"
                        },
                        new
                        {
                            Id = new Guid("70557e42-0145-405a-b517-5c5d0aff46c1"),
                            Name = "Lesotho",
                            RegioneCode = "LSO"
                        },
                        new
                        {
                            Id = new Guid("3ff5dac9-dc46-488c-b9e9-13ee966a9a89"),
                            Name = "Liberia",
                            RegioneCode = "LBR"
                        },
                        new
                        {
                            Id = new Guid("fed9a761-08e7-419d-a492-1e6c48f46871"),
                            Name = "Libya",
                            RegioneCode = "LBY"
                        },
                        new
                        {
                            Id = new Guid("f346e252-a66e-4a4f-a5ff-355bfe5278d9"),
                            Name = "Liechtenstein",
                            RegioneCode = "LIE"
                        },
                        new
                        {
                            Id = new Guid("567c7931-64f7-4550-9104-993c65763c31"),
                            Name = "Lithuania",
                            RegioneCode = "LTU"
                        },
                        new
                        {
                            Id = new Guid("0101ff6d-07ea-41bc-a333-135364750871"),
                            Name = "Luxembourg",
                            RegioneCode = "LUX"
                        },
                        new
                        {
                            Id = new Guid("bf9d86f4-0259-437e-9158-0c64ea2e4908"),
                            Name = "Macao",
                            RegioneCode = "MAC"
                        },
                        new
                        {
                            Id = new Guid("92b59f12-67bf-4af8-9e36-7c85c4157f34"),
                            Name = "Madagascar",
                            RegioneCode = "MDG"
                        },
                        new
                        {
                            Id = new Guid("2c7e8888-9290-469b-838e-b00eb5dec82c"),
                            Name = "Malawi",
                            RegioneCode = "MWI"
                        },
                        new
                        {
                            Id = new Guid("1c3a7637-71c0-4fbf-8961-544bc244a026"),
                            Name = "Malaysia",
                            RegioneCode = "MYS"
                        },
                        new
                        {
                            Id = new Guid("fbd22e13-4904-40a2-9226-891c9e37f545"),
                            Name = "Maldives",
                            RegioneCode = "MDV"
                        },
                        new
                        {
                            Id = new Guid("1e1a95b3-9b08-4a75-acce-8df68ba91961"),
                            Name = "Mali",
                            RegioneCode = "MLI"
                        },
                        new
                        {
                            Id = new Guid("3784dc7c-ac72-4740-bb27-180d1b7b2bf9"),
                            Name = "Malta",
                            RegioneCode = "MLT"
                        },
                        new
                        {
                            Id = new Guid("f404b953-fee8-4fd1-8fc3-b98376854611"),
                            Name = "Marshall Islands",
                            RegioneCode = "MHL"
                        },
                        new
                        {
                            Id = new Guid("855d8836-1170-493a-b6ca-ce78004c3dc6"),
                            Name = "Martinique",
                            RegioneCode = "MTQ"
                        },
                        new
                        {
                            Id = new Guid("2934d47e-295f-4dd2-b01e-a3705143b92d"),
                            Name = "Mauritania",
                            RegioneCode = "MRT"
                        },
                        new
                        {
                            Id = new Guid("2713665f-68d3-46bc-836e-458cae90822b"),
                            Name = "Mauritius",
                            RegioneCode = "MUS"
                        },
                        new
                        {
                            Id = new Guid("3c236c8d-c8a2-4419-849c-f7782ee46088"),
                            Name = "Mayotte",
                            RegioneCode = "MYT"
                        },
                        new
                        {
                            Id = new Guid("090c428f-fd76-464d-aefc-a72e98272075"),
                            Name = "Mexico",
                            RegioneCode = "MEX"
                        },
                        new
                        {
                            Id = new Guid("db494eac-17f3-4199-bb7b-c85315de067e"),
                            Name = "Micronesia (Federated States of)",
                            RegioneCode = "FSM"
                        },
                        new
                        {
                            Id = new Guid("a78c31ca-d55d-439e-b035-2faa7611820e"),
                            Name = "Moldova, Republic of",
                            RegioneCode = "MDA"
                        },
                        new
                        {
                            Id = new Guid("6e3a6afc-dc11-4efc-9ee5-d45a886543cd"),
                            Name = "Monaco",
                            RegioneCode = "MCO"
                        },
                        new
                        {
                            Id = new Guid("483bcaf9-0883-483a-9a6b-ad4fd35ff342"),
                            Name = "Mongolia",
                            RegioneCode = "MNG"
                        },
                        new
                        {
                            Id = new Guid("f39ce47d-20eb-4c02-a90c-acfd2d801200"),
                            Name = "Montenegro",
                            RegioneCode = "MNE"
                        },
                        new
                        {
                            Id = new Guid("0e584561-4e3e-4fac-91c2-dcc304a188f6"),
                            Name = "Montserrat",
                            RegioneCode = "MSR"
                        },
                        new
                        {
                            Id = new Guid("352c0ed1-5175-4526-a6b4-5fb86334bb2d"),
                            Name = "Morocco",
                            RegioneCode = "MAR"
                        },
                        new
                        {
                            Id = new Guid("0367a937-51a8-4b3a-b227-f2c714d4735e"),
                            Name = "Mozambique",
                            RegioneCode = "MOZ"
                        },
                        new
                        {
                            Id = new Guid("03444756-c9e2-485e-8458-5960956a0d16"),
                            Name = "Myanmar",
                            RegioneCode = "MMR"
                        },
                        new
                        {
                            Id = new Guid("0b415a8d-952e-4a63-8089-64cdf7505ae5"),
                            Name = "Namibia",
                            RegioneCode = "NAM"
                        },
                        new
                        {
                            Id = new Guid("7fcf8d00-64b9-4019-a726-32aac7e25393"),
                            Name = "Nauru",
                            RegioneCode = "NRU"
                        },
                        new
                        {
                            Id = new Guid("e510b38a-09e3-48e9-a7fd-6c010a38ca34"),
                            Name = "Nepal",
                            RegioneCode = "NPL"
                        },
                        new
                        {
                            Id = new Guid("98478c9e-4483-43af-ab88-2c8a388cd2a1"),
                            Name = "Netherlands",
                            RegioneCode = "NLD"
                        },
                        new
                        {
                            Id = new Guid("a5abcc74-893d-4ff4-a207-7ef89d9005c9"),
                            Name = "New Caledonia",
                            RegioneCode = "NCL"
                        },
                        new
                        {
                            Id = new Guid("0d8ab0e0-41ff-4561-b52d-e1b79ff825aa"),
                            Name = "New Zealand",
                            RegioneCode = "NZL"
                        },
                        new
                        {
                            Id = new Guid("cecc5511-a2ea-4a8e-8311-c43175b09397"),
                            Name = "Nicaragua",
                            RegioneCode = "NIC"
                        },
                        new
                        {
                            Id = new Guid("3c52c724-ad05-4fae-8390-542c201c81b8"),
                            Name = "Niger",
                            RegioneCode = "NER"
                        },
                        new
                        {
                            Id = new Guid("70824528-59a8-4437-a802-47e70b6017ee"),
                            Name = "Nigeria",
                            RegioneCode = "NGA"
                        },
                        new
                        {
                            Id = new Guid("fbaf7237-0f64-48c3-b4c9-b729e8e68df3"),
                            Name = "Niue",
                            RegioneCode = "NIU"
                        },
                        new
                        {
                            Id = new Guid("8ed54c9f-ec6f-4515-ada3-569dc855944c"),
                            Name = "Norfolk Island",
                            RegioneCode = "NFK"
                        },
                        new
                        {
                            Id = new Guid("c3ba17e9-c383-456a-af5b-c668d9bffa5e"),
                            Name = "North Macedonia",
                            RegioneCode = "MKD"
                        },
                        new
                        {
                            Id = new Guid("c992f142-73ff-4d79-b1b4-353c50ee911f"),
                            Name = "Northern Mariana Islands",
                            RegioneCode = "MNP"
                        },
                        new
                        {
                            Id = new Guid("be9f403e-d045-4188-867b-0a36deb99f77"),
                            Name = "Norway",
                            RegioneCode = "NOR"
                        },
                        new
                        {
                            Id = new Guid("950959ff-35cb-46da-a435-3ff01d0c88e2"),
                            Name = "Oman",
                            RegioneCode = "OMN"
                        },
                        new
                        {
                            Id = new Guid("7f596dac-f3dc-423a-8368-a0f31a0abed3"),
                            Name = "Pakistan",
                            RegioneCode = "PAK"
                        },
                        new
                        {
                            Id = new Guid("4b7aa8b0-7713-407b-b06c-f467a522ce08"),
                            Name = "Palau",
                            RegioneCode = "PLW"
                        },
                        new
                        {
                            Id = new Guid("f2c1b5ba-0191-4e67-a890-c8cb9faf684a"),
                            Name = "Palestine, State of",
                            RegioneCode = "PSE"
                        },
                        new
                        {
                            Id = new Guid("51bb855c-1e3c-431a-bcd0-a17e54a303ea"),
                            Name = "Panama",
                            RegioneCode = "PAN"
                        },
                        new
                        {
                            Id = new Guid("c8f30883-962a-4462-9357-0747da55151e"),
                            Name = "Papua New Guinea",
                            RegioneCode = "PNG"
                        },
                        new
                        {
                            Id = new Guid("fab433f1-08d1-4759-8afc-1e4210a7783c"),
                            Name = "Paraguay",
                            RegioneCode = "PRY"
                        },
                        new
                        {
                            Id = new Guid("c89fc0d5-2564-48cf-8003-c048dd294010"),
                            Name = "Peru",
                            RegioneCode = "PER"
                        },
                        new
                        {
                            Id = new Guid("baa3e035-0181-404a-a5f8-c3980c1ce675"),
                            Name = "Philippines",
                            RegioneCode = "PHL"
                        },
                        new
                        {
                            Id = new Guid("59a4d65c-6417-4b80-96b2-f076a924f6ce"),
                            Name = "Pitcairn",
                            RegioneCode = "PCN"
                        },
                        new
                        {
                            Id = new Guid("4957da7a-e5e7-4a4d-982b-09d88d4a58b4"),
                            Name = "Poland",
                            RegioneCode = "POL"
                        },
                        new
                        {
                            Id = new Guid("ce700e52-a116-4bf0-85ed-a8db59caab46"),
                            Name = "Portugal",
                            RegioneCode = "PRT"
                        },
                        new
                        {
                            Id = new Guid("bbf1c954-5390-4488-b309-d3ec6d027dd2"),
                            Name = "Puerto Rico",
                            RegioneCode = "PRI"
                        },
                        new
                        {
                            Id = new Guid("fcbbe8df-4e4f-45a5-b803-3519a075bb3e"),
                            Name = "Qatar",
                            RegioneCode = "QAT"
                        },
                        new
                        {
                            Id = new Guid("63efded4-bc57-445f-b703-981e7eca8907"),
                            Name = "Réunion",
                            RegioneCode = "REU"
                        },
                        new
                        {
                            Id = new Guid("2cb6716d-44fd-48f2-a123-f298909e682b"),
                            Name = "Romania",
                            RegioneCode = "ROU"
                        },
                        new
                        {
                            Id = new Guid("eecc4787-2310-4331-b2b7-84036ccab00a"),
                            Name = "Russian Federation",
                            RegioneCode = "RUS"
                        },
                        new
                        {
                            Id = new Guid("bf0e880e-b1cd-4db1-9050-ef04ca780d57"),
                            Name = "Rwanda",
                            RegioneCode = "RWA"
                        },
                        new
                        {
                            Id = new Guid("8dbef785-3def-4933-829d-e64b564fa749"),
                            Name = "Saint Barthélemy",
                            RegioneCode = "BLM"
                        },
                        new
                        {
                            Id = new Guid("cddef1f1-e474-44a3-a11d-83deb1aedd69"),
                            Name = "Saint Helena, Ascension and Tristan da Cunha",
                            RegioneCode = "SHN"
                        },
                        new
                        {
                            Id = new Guid("a304c9e0-8b99-420b-99a9-55f982085e60"),
                            Name = "Saint Kitts and Nevis",
                            RegioneCode = "KNA"
                        },
                        new
                        {
                            Id = new Guid("d22c6d83-539e-4b9e-a7da-588ba42c1b13"),
                            Name = "Saint Lucia",
                            RegioneCode = "LCA"
                        },
                        new
                        {
                            Id = new Guid("8e6681d9-1a4a-42d1-9b15-9124ca0e731b"),
                            Name = "Saint Martin (French part)",
                            RegioneCode = "MAF"
                        },
                        new
                        {
                            Id = new Guid("72bd85fb-d407-454c-b56d-2545bb9a3163"),
                            Name = "Saint Pierre and Miquelon",
                            RegioneCode = "SPM"
                        },
                        new
                        {
                            Id = new Guid("26869242-ed06-4ecd-af8d-c6f5cf2dbde1"),
                            Name = "Saint Vincent and the Grenadines",
                            RegioneCode = "VCT"
                        },
                        new
                        {
                            Id = new Guid("8d729739-8078-4f61-bbe5-4dc5c3b3f0f5"),
                            Name = "Samoa",
                            RegioneCode = "WSM"
                        },
                        new
                        {
                            Id = new Guid("95ac011a-d215-45a1-ae69-2b0fef7484c8"),
                            Name = "San Marino",
                            RegioneCode = "SMR"
                        },
                        new
                        {
                            Id = new Guid("d74ce2da-f161-439d-9d28-7a2f978c1e32"),
                            Name = "Sao Tome and Principe",
                            RegioneCode = "STP"
                        },
                        new
                        {
                            Id = new Guid("aefde2cd-8432-40f9-8412-4dbfdc37a44c"),
                            Name = "Saudi Arabia",
                            RegioneCode = "SAU"
                        },
                        new
                        {
                            Id = new Guid("1b9ab440-e873-4cfa-a240-712ab853c74b"),
                            Name = "Senegal",
                            RegioneCode = "SEN"
                        },
                        new
                        {
                            Id = new Guid("476696b8-6b65-4037-a13f-fc016039c38e"),
                            Name = "Serbia",
                            RegioneCode = "SRB"
                        },
                        new
                        {
                            Id = new Guid("bd0e60cd-0ae5-4bae-87c9-1281c332ef2e"),
                            Name = "Seychelles",
                            RegioneCode = "SYC"
                        },
                        new
                        {
                            Id = new Guid("f22cff9a-e540-4553-9ad0-7853803a776d"),
                            Name = "Sierra Leone",
                            RegioneCode = "SLE"
                        },
                        new
                        {
                            Id = new Guid("3e3ec23e-1289-4777-a60a-fe2ba3b5462b"),
                            Name = "Singapore",
                            RegioneCode = "SGP"
                        },
                        new
                        {
                            Id = new Guid("7637fafb-b984-462a-ab61-c66a9d38ab63"),
                            Name = "Sint Maarten (Dutch part)",
                            RegioneCode = "SXM"
                        },
                        new
                        {
                            Id = new Guid("7318e8dc-4fc1-49df-bb58-816fda9a0337"),
                            Name = "Slovakia",
                            RegioneCode = "SVK"
                        },
                        new
                        {
                            Id = new Guid("ab0bc840-59d3-42ba-9133-1359fcea1a98"),
                            Name = "Slovenia",
                            RegioneCode = "SVN"
                        },
                        new
                        {
                            Id = new Guid("e8491314-2068-4e37-a5a2-45ad470ecd60"),
                            Name = "Solomon Islands",
                            RegioneCode = "SLB"
                        },
                        new
                        {
                            Id = new Guid("9302db2f-f71a-4ca0-8558-9c6ada76456a"),
                            Name = "Somalia",
                            RegioneCode = "SOM"
                        },
                        new
                        {
                            Id = new Guid("0b6c7c28-bf8b-4fd1-9756-fcacae1ed891"),
                            Name = "South Africa",
                            RegioneCode = "ZAF"
                        },
                        new
                        {
                            Id = new Guid("049091b8-c64a-4030-963e-5bc11a77c3ea"),
                            Name = "South Georgia and the South Sandwich Islands",
                            RegioneCode = "SGS"
                        },
                        new
                        {
                            Id = new Guid("3c0328ef-87e9-412e-9eb1-3ca1d6f16ab3"),
                            Name = "South Sudan",
                            RegioneCode = "SSD"
                        },
                        new
                        {
                            Id = new Guid("c7e2bddc-9717-42d1-a2af-e0258ccda160"),
                            Name = "Spain",
                            RegioneCode = "ESP"
                        },
                        new
                        {
                            Id = new Guid("a866e93e-35fd-44a1-81ea-0e8811a9ece5"),
                            Name = "Sri Lanka",
                            RegioneCode = "LKA"
                        },
                        new
                        {
                            Id = new Guid("678f3bca-888e-4db5-90a1-c31dc3230e7f"),
                            Name = "Sudan",
                            RegioneCode = "SDN"
                        },
                        new
                        {
                            Id = new Guid("5a027f90-b79c-44bf-9f1d-661c85911d65"),
                            Name = "Suriname",
                            RegioneCode = "SUR"
                        },
                        new
                        {
                            Id = new Guid("8c52ef52-4380-48c7-8a46-046983e33cb8"),
                            Name = "Svalbard and Jan Mayen",
                            RegioneCode = "SJM"
                        },
                        new
                        {
                            Id = new Guid("5770a7b9-2c21-4d37-909b-d2a17c0c7a2f"),
                            Name = "Sweden",
                            RegioneCode = "SWE"
                        },
                        new
                        {
                            Id = new Guid("eb18d5e8-6489-4c75-8934-6b3e7c441b11"),
                            Name = "Switzerland",
                            RegioneCode = "CHE"
                        },
                        new
                        {
                            Id = new Guid("f6dd679e-7db0-4da5-9a3c-a93cfad7d664"),
                            Name = "Syrian Arab Republic",
                            RegioneCode = "SYR"
                        },
                        new
                        {
                            Id = new Guid("ce6f9d26-155a-494c-a4e3-35f27cf288b9"),
                            Name = "Taiwan, Province of China",
                            RegioneCode = "TWN"
                        },
                        new
                        {
                            Id = new Guid("c8880fa8-24d5-4020-b7d0-3113b2e72495"),
                            Name = "Tajikistan",
                            RegioneCode = "TJK"
                        },
                        new
                        {
                            Id = new Guid("de0fe66d-c987-45d9-b980-b1ec6ac0e1bd"),
                            Name = "Tanzania, United Republic of",
                            RegioneCode = "TZA"
                        },
                        new
                        {
                            Id = new Guid("35d3fd7b-eedb-418d-b6e9-90f7785b573a"),
                            Name = "Thailand",
                            RegioneCode = "THA"
                        },
                        new
                        {
                            Id = new Guid("6e1f14db-b837-4726-9b96-ac697f4996de"),
                            Name = "Timor-Leste",
                            RegioneCode = "TLS"
                        },
                        new
                        {
                            Id = new Guid("2b06a269-1d04-4bf2-af36-c9f361ad788c"),
                            Name = "Togo",
                            RegioneCode = "TGO"
                        },
                        new
                        {
                            Id = new Guid("3c8105e2-891d-438a-88a6-5f2a4d18e633"),
                            Name = "Tokelau",
                            RegioneCode = "TKL"
                        },
                        new
                        {
                            Id = new Guid("06d38b68-8685-4e95-860f-6d87e1975bae"),
                            Name = "Tonga",
                            RegioneCode = "TON"
                        },
                        new
                        {
                            Id = new Guid("fbca0aa4-423f-4249-8b70-72d505a606ca"),
                            Name = "Trinidad and Tobago",
                            RegioneCode = "TTO"
                        },
                        new
                        {
                            Id = new Guid("baee5c83-2005-4778-acec-92443bbbd12a"),
                            Name = "Tunisia",
                            RegioneCode = "TUN"
                        },
                        new
                        {
                            Id = new Guid("940f282e-6437-420b-8350-13130cddec05"),
                            Name = "Turkey",
                            RegioneCode = "TUR"
                        },
                        new
                        {
                            Id = new Guid("de7f691f-124e-4b5f-8274-42c90c9d1ba3"),
                            Name = "Turkmenistan",
                            RegioneCode = "TKM"
                        },
                        new
                        {
                            Id = new Guid("a60120ba-f2cf-48e9-a0a0-63afa9408622"),
                            Name = "Turks and Caicos Islands",
                            RegioneCode = "TCA"
                        },
                        new
                        {
                            Id = new Guid("d3b79d2c-82ae-4696-9f4c-12cd764c3a71"),
                            Name = "Tuvalu",
                            RegioneCode = "TUV"
                        },
                        new
                        {
                            Id = new Guid("103333bc-e1e2-4417-b9ba-8901934d3290"),
                            Name = "Uganda",
                            RegioneCode = "UGA"
                        },
                        new
                        {
                            Id = new Guid("bd339386-c85e-4e65-91a7-9796cd13bf4f"),
                            Name = "Ukraine",
                            RegioneCode = "UKR"
                        },
                        new
                        {
                            Id = new Guid("de7cee70-f6fe-4848-92a6-1f6a0c641bd5"),
                            Name = "United Arab Emirates",
                            RegioneCode = "ARE"
                        },
                        new
                        {
                            Id = new Guid("53a6908b-261b-40af-96e9-d038e6f8ea67"),
                            Name = "United Kingdom of Great Britain and Northern Ireland",
                            RegioneCode = "GBR"
                        },
                        new
                        {
                            Id = new Guid("32ca3434-2aab-4da9-84b8-51f5a02f4fb0"),
                            Name = "United States of America",
                            RegioneCode = "USA"
                        },
                        new
                        {
                            Id = new Guid("c455b9c4-3fbc-40ee-84bb-07b5dceaca45"),
                            Name = "United States Minor Outlying Islands",
                            RegioneCode = "UMI"
                        },
                        new
                        {
                            Id = new Guid("6e621a84-082b-401a-a7c7-798c89996b89"),
                            Name = "Uruguay",
                            RegioneCode = "URY"
                        },
                        new
                        {
                            Id = new Guid("f0edfc8d-2aae-4e12-a0dd-222009cd043d"),
                            Name = "Uzbekistan",
                            RegioneCode = "UZB"
                        },
                        new
                        {
                            Id = new Guid("2c67bf06-a319-4fad-8e05-51015038c7e0"),
                            Name = "Vanuatu",
                            RegioneCode = "VUT"
                        },
                        new
                        {
                            Id = new Guid("febaeda1-1a1e-441a-a56a-ea6d413981b8"),
                            Name = "Venezuela (Bolivarian Republic of)",
                            RegioneCode = "VEN"
                        },
                        new
                        {
                            Id = new Guid("140e9df2-1bd3-4570-837b-b4dc1f6f595f"),
                            Name = "Viet Nam",
                            RegioneCode = "VNM"
                        },
                        new
                        {
                            Id = new Guid("4a37fcdb-4e03-4ca4-870c-7d7bfd2ecf70"),
                            Name = "Virgin Islands (British)",
                            RegioneCode = "VGB"
                        },
                        new
                        {
                            Id = new Guid("e72810f4-49be-4a59-a637-3bf9876fdb68"),
                            Name = "Virgin Islands (U.S.)",
                            RegioneCode = "VIR"
                        },
                        new
                        {
                            Id = new Guid("8a37fef9-32e9-4b44-af93-8d06fbc6bb64"),
                            Name = "Wallis and Futuna",
                            RegioneCode = "WLF"
                        },
                        new
                        {
                            Id = new Guid("ad4e18a2-5674-4626-b6f6-6a63f4e86898"),
                            Name = "Western Sahara",
                            RegioneCode = "ESH"
                        },
                        new
                        {
                            Id = new Guid("bacdd7af-593c-4a76-aeaf-a7589fdc6699"),
                            Name = "Yemen",
                            RegioneCode = "YEM"
                        },
                        new
                        {
                            Id = new Guid("39227311-c6c7-4d02-b7b4-c5a4332b91b1"),
                            Name = "Zambia",
                            RegioneCode = "ZMB"
                        },
                        new
                        {
                            Id = new Guid("28bfaac8-294d-48d1-8ae5-ce0e703041af"),
                            Name = "Zimbabwe",
                            RegioneCode = "ZWE"
                        });
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Enities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Enities.RoleClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RoleId");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Enities.Security.SecurityCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("CodeActionType");

                    b.Property<string>("Provider");

                    b.Property<int>("ProviderType");

                    b.HasKey("Id");

                    b.ToTable("SecurityCodes");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Enities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<Guid?>("CountryId");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Enities.UserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Enities.User", b =>
                {
                    b.HasOne("AspNetCoreSpa.Domain.Enities.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Enities.UserRole", b =>
                {
                    b.HasOne("AspNetCoreSpa.Domain.Enities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCoreSpa.Domain.Enities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
