// <auto-generated />
using System;
using AspNetCoreSpa.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreSpa.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200307194712_Fill_Countries")]
    partial class Fill_Countries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("RegionCode")
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a6ccdee-7cb5-4f7d-a138-a0280ae18434"),
                            Name = "Afghanistan",
                            RegionCode = "AFG"
                        },
                        new
                        {
                            Id = new Guid("d67accbb-525b-4d95-83b4-f568d8b9ebda"),
                            Name = "Albania",
                            RegionCode = "ALB"
                        },
                        new
                        {
                            Id = new Guid("673a513c-141a-4175-b7b8-54f2741e5b9c"),
                            Name = "Algeria",
                            RegionCode = "DZA"
                        },
                        new
                        {
                            Id = new Guid("73155220-36c2-4011-98de-c3cfbea2981c"),
                            Name = "American Samoa",
                            RegionCode = "ASM"
                        },
                        new
                        {
                            Id = new Guid("2f0cdc4b-6850-4172-a2aa-59d28d04ebc9"),
                            Name = "Andorra",
                            RegionCode = "AND"
                        },
                        new
                        {
                            Id = new Guid("ce6daf31-2239-4448-a79a-42f3d58a3258"),
                            Name = "Angola",
                            RegionCode = "AGO"
                        },
                        new
                        {
                            Id = new Guid("ad27c9cf-b81c-4ae7-bfd4-84cfd92e911d"),
                            Name = "Anguilla",
                            RegionCode = "AIA"
                        },
                        new
                        {
                            Id = new Guid("e44fb2a3-c535-492a-ae6c-fe67fe338c21"),
                            Name = "Antigua and Barbuda",
                            RegionCode = "ATG"
                        },
                        new
                        {
                            Id = new Guid("58edadf2-91aa-405b-a52d-bf4040df45c5"),
                            Name = "Argentina",
                            RegionCode = "ARG"
                        },
                        new
                        {
                            Id = new Guid("219238e8-dfbe-4142-b3f4-47ecdd5c8f5e"),
                            Name = "Armenia",
                            RegionCode = "ARM"
                        },
                        new
                        {
                            Id = new Guid("eb3359ad-d4fe-465b-98b1-e633cc92bc06"),
                            Name = "Aruba",
                            RegionCode = "ABW"
                        },
                        new
                        {
                            Id = new Guid("9eac06ed-c820-4c8c-8915-f9105556b90d"),
                            Name = "Australia",
                            RegionCode = "AUS"
                        },
                        new
                        {
                            Id = new Guid("694aad40-f8e3-4f84-8fe1-1afb48f8cb3d"),
                            Name = "Austria",
                            RegionCode = "AUT"
                        },
                        new
                        {
                            Id = new Guid("a8b621dc-9d3f-4aee-9a70-e0c203dfec1d"),
                            Name = "Azerbaijan",
                            RegionCode = "AZE"
                        },
                        new
                        {
                            Id = new Guid("dc3c7cea-5ce5-4f1f-a063-5886dff190af"),
                            Name = "Bahrain",
                            RegionCode = "BHR"
                        },
                        new
                        {
                            Id = new Guid("144d772f-1036-4dae-9b3c-a7fcddf11824"),
                            Name = "Bangladesh",
                            RegionCode = "BGD"
                        },
                        new
                        {
                            Id = new Guid("a6d0522f-d1bc-43c8-acb9-3cb76e1c2ec8"),
                            Name = "Barbados",
                            RegionCode = "BRB"
                        },
                        new
                        {
                            Id = new Guid("5d2553c6-fb7c-4e2a-84b1-c1d092f24539"),
                            Name = "Belarus",
                            RegionCode = "BLR"
                        },
                        new
                        {
                            Id = new Guid("4a3425ae-6a3c-4a4c-9496-10ac6cc27d50"),
                            Name = "Belgium",
                            RegionCode = "BEL"
                        },
                        new
                        {
                            Id = new Guid("35361cc0-ce05-4413-9eed-5b2ae625f966"),
                            Name = "Belize",
                            RegionCode = "BLZ"
                        },
                        new
                        {
                            Id = new Guid("828f9137-a10b-49e1-afef-aa90ea66296a"),
                            Name = "Benin",
                            RegionCode = "BEN"
                        },
                        new
                        {
                            Id = new Guid("97cd6b4e-25c9-48a6-a1b2-49dd19b3061d"),
                            Name = "Bermuda",
                            RegionCode = "BMU"
                        },
                        new
                        {
                            Id = new Guid("36fc9479-812f-4ce3-bccc-cd73ae61225f"),
                            Name = "Bhutan",
                            RegionCode = "BTN"
                        },
                        new
                        {
                            Id = new Guid("9f102ae1-5116-4bcf-9ef0-c18ecaa28663"),
                            Name = "Bolivia",
                            RegionCode = "BOL"
                        },
                        new
                        {
                            Id = new Guid("3305ce72-7a64-4e8c-bd00-7e9c00c912f4"),
                            Name = "Bonaire, Sint Eustatius and Saba",
                            RegionCode = "BES"
                        },
                        new
                        {
                            Id = new Guid("33d7f0a1-8cc7-48e2-a653-d290846e2ac4"),
                            Name = "Bosnia and Herzegovina",
                            RegionCode = "BIH"
                        },
                        new
                        {
                            Id = new Guid("d76e82a3-529c-4f8a-b9f9-a93e581c3196"),
                            Name = "Botswana",
                            RegionCode = "BWA"
                        },
                        new
                        {
                            Id = new Guid("9bd7e393-e95b-477e-9dd0-5b55dec0bc53"),
                            Name = "Brazil",
                            RegionCode = "BRA"
                        },
                        new
                        {
                            Id = new Guid("60c46921-6d88-4d2e-9a4d-8f4d149d3bc1"),
                            Name = "British Indian Ocean Territory",
                            RegionCode = "IOT"
                        },
                        new
                        {
                            Id = new Guid("1c63135e-6377-4ec2-bfe9-5182debf7284"),
                            Name = "British Virgin Islands",
                            RegionCode = "VGB"
                        },
                        new
                        {
                            Id = new Guid("8329b6bf-a79a-4670-94f9-aafc437e176b"),
                            Name = "Brunei Darussalam",
                            RegionCode = "BRN"
                        },
                        new
                        {
                            Id = new Guid("0b2c02c8-12e9-470b-b73e-8dee524ece33"),
                            Name = "Bulgaria",
                            RegionCode = "BGR"
                        },
                        new
                        {
                            Id = new Guid("27ec05e6-99a7-4476-9670-bf6efdef1822"),
                            Name = "Burkina Faso",
                            RegionCode = "BFA"
                        },
                        new
                        {
                            Id = new Guid("cf827c66-9701-4f20-8ac4-5980ede49b24"),
                            Name = "Myanmar",
                            RegionCode = "MMR"
                        },
                        new
                        {
                            Id = new Guid("99dbbdf2-efd3-4796-9da4-74ab77efe689"),
                            Name = "Burundi",
                            RegionCode = "BDI"
                        },
                        new
                        {
                            Id = new Guid("d985a4c7-9225-4753-8bec-af4af19d03a4"),
                            Name = "Cambodia",
                            RegionCode = "KHM"
                        },
                        new
                        {
                            Id = new Guid("439e5deb-07d5-4b9d-9cfa-8c8edd3f9c6f"),
                            Name = "Cameroon",
                            RegionCode = "CMR"
                        },
                        new
                        {
                            Id = new Guid("cf38b8ba-fe1e-46d0-8a54-145bba370af4"),
                            Name = "Canada",
                            RegionCode = "CAN"
                        },
                        new
                        {
                            Id = new Guid("98c13966-de3b-4663-9be6-df7875065092"),
                            Name = "Cabo Verde",
                            RegionCode = "CPV"
                        },
                        new
                        {
                            Id = new Guid("24e63bf3-791e-45b9-b608-f2dc2ae9a013"),
                            Name = "Cayman Islands",
                            RegionCode = "CYM"
                        },
                        new
                        {
                            Id = new Guid("9272bddc-4c44-4062-a1d1-cc5e136bbd09"),
                            Name = "Central African Republic",
                            RegionCode = "CAF"
                        },
                        new
                        {
                            Id = new Guid("0881abb3-a144-4d0d-8fdf-09a9d3fd9680"),
                            Name = "Chad",
                            RegionCode = "TCD"
                        },
                        new
                        {
                            Id = new Guid("78146aa4-3d13-4802-b94a-1fd9da247b9f"),
                            Name = "Chile",
                            RegionCode = "CHL"
                        },
                        new
                        {
                            Id = new Guid("f4f4af18-22ec-407f-9987-81d3b8b0ffc8"),
                            Name = "China",
                            RegionCode = "CHN"
                        },
                        new
                        {
                            Id = new Guid("5eae5887-8601-4138-9d52-5a2ceb763644"),
                            Name = "Colombia",
                            RegionCode = "COL"
                        },
                        new
                        {
                            Id = new Guid("703a767b-a4b4-4393-9aa2-9f2bb638e2e8"),
                            Name = "Comoros",
                            RegionCode = "COM"
                        },
                        new
                        {
                            Id = new Guid("7ae4db89-8c8d-4e4c-b16e-a20306bbb1e1"),
                            Name = "Cook Islands",
                            RegionCode = "COK"
                        },
                        new
                        {
                            Id = new Guid("c3f25679-15dc-472e-af78-b2675bf5e284"),
                            Name = "Costa Rica",
                            RegionCode = "CRI"
                        },
                        new
                        {
                            Id = new Guid("6f7f4cdb-3849-4b9e-9145-69a1f07d3304"),
                            Name = "Côte dIvoire",
                            RegionCode = "CIV"
                        },
                        new
                        {
                            Id = new Guid("28454fee-cafe-43ea-b6b9-d2901dcd00d8"),
                            Name = "Croatia",
                            RegionCode = "HRV"
                        },
                        new
                        {
                            Id = new Guid("6bb50cc3-64d7-4c3b-8b02-ae1fdb909764"),
                            Name = "Cuba",
                            RegionCode = "CUB"
                        },
                        new
                        {
                            Id = new Guid("c729fd06-8453-4609-9246-97f577d6329a"),
                            Name = "Curaçao",
                            RegionCode = "CUW"
                        },
                        new
                        {
                            Id = new Guid("ab9700a9-8475-4a2a-9e30-617479000848"),
                            Name = "Cyprus",
                            RegionCode = "CYP"
                        },
                        new
                        {
                            Id = new Guid("c8a2b90f-83f7-4573-a957-20bb17623cf6"),
                            Name = "Czechia",
                            RegionCode = "CZE"
                        },
                        new
                        {
                            Id = new Guid("4535aa6c-02f4-4a68-9ec3-079168dfa269"),
                            Name = "Denmark",
                            RegionCode = "DNK"
                        },
                        new
                        {
                            Id = new Guid("cee404b0-56f3-4fa7-b736-17dd3d9dee25"),
                            Name = "Djibouti",
                            RegionCode = "DJI"
                        },
                        new
                        {
                            Id = new Guid("8a1b58da-1f38-4ef2-aa2b-c79c3b170507"),
                            Name = "Dominica",
                            RegionCode = "DMA"
                        },
                        new
                        {
                            Id = new Guid("e25bce5d-c337-4dd4-93fd-6f8e94f08d03"),
                            Name = "Dominican Republic",
                            RegionCode = "DOM"
                        },
                        new
                        {
                            Id = new Guid("c7afdb0d-d3e0-4190-b490-4627d60c7b24"),
                            Name = "Ecuador",
                            RegionCode = "ECU"
                        },
                        new
                        {
                            Id = new Guid("45efd885-0ee0-4f17-b668-909c4df57e08"),
                            Name = "Egypt",
                            RegionCode = "EGY"
                        },
                        new
                        {
                            Id = new Guid("02d59fec-7e67-4fea-bbe2-cd9383f9fa1d"),
                            Name = "El Salvador",
                            RegionCode = "SLV"
                        },
                        new
                        {
                            Id = new Guid("f9a56b1d-a894-48d2-b63d-17bf5dbe8c34"),
                            Name = "Equatorial Guinea",
                            RegionCode = "GNQ"
                        },
                        new
                        {
                            Id = new Guid("a79b95a1-8b33-450f-a1e4-ed816a97841a"),
                            Name = "Eritrea",
                            RegionCode = "ERI"
                        },
                        new
                        {
                            Id = new Guid("a428fc44-7c9b-4239-a7d2-515966cfd972"),
                            Name = "Estonia",
                            RegionCode = "EST"
                        },
                        new
                        {
                            Id = new Guid("44d99676-ec83-46f3-b90b-46159a4a1500"),
                            Name = "Ethiopia",
                            RegionCode = "ETH"
                        },
                        new
                        {
                            Id = new Guid("905697e2-ee4a-41bc-9224-bb0d4a6d7a9e"),
                            Name = "Falkland Islands",
                            RegionCode = "FLK"
                        },
                        new
                        {
                            Id = new Guid("7e677911-79b8-43b2-a356-2261eb642d67"),
                            Name = "Faroe Islands",
                            RegionCode = "FRO"
                        },
                        new
                        {
                            Id = new Guid("ef888bda-ab5c-4aa7-8949-4619ab56b6a5"),
                            Name = "Federated States of Micronesia",
                            RegionCode = "FSM"
                        },
                        new
                        {
                            Id = new Guid("1cd55df4-0887-40d9-98c7-54f48805bdac"),
                            Name = "Fiji",
                            RegionCode = "FJI"
                        },
                        new
                        {
                            Id = new Guid("6da8d7f6-2a4d-47f6-90a0-903715ba9d6b"),
                            Name = "Finland",
                            RegionCode = "FIN"
                        },
                        new
                        {
                            Id = new Guid("a090bb45-52f6-4f43-a9ba-70151a966f44"),
                            Name = "France",
                            RegionCode = "FRA"
                        },
                        new
                        {
                            Id = new Guid("fceee3f9-7111-4a00-a175-35560726cfc5"),
                            Name = "French Guiana",
                            RegionCode = "GUF"
                        },
                        new
                        {
                            Id = new Guid("9f27c12a-b015-4fc4-905b-9d193b774d65"),
                            Name = "French Polynesia",
                            RegionCode = "PYF"
                        },
                        new
                        {
                            Id = new Guid("51302767-5984-4a24-a2be-5b3fac89ddb9"),
                            Name = "Gabon",
                            RegionCode = "GAB"
                        },
                        new
                        {
                            Id = new Guid("9c899c11-ac55-4cbd-84d5-0d068af5269b"),
                            Name = "Georgia",
                            RegionCode = "GEO"
                        },
                        new
                        {
                            Id = new Guid("028d5555-f865-4849-8d9e-38add4ed3652"),
                            Name = "Germany",
                            RegionCode = "DEU"
                        },
                        new
                        {
                            Id = new Guid("9b9dde4a-103e-4d5c-be3c-14a6400928fc"),
                            Name = "Ghana",
                            RegionCode = "GHA"
                        },
                        new
                        {
                            Id = new Guid("8ea7a073-3a21-4a68-a48f-7cd8147d3aa8"),
                            Name = "Gibraltar",
                            RegionCode = "GIB"
                        },
                        new
                        {
                            Id = new Guid("0cbdf9a3-7423-44a4-b913-1998e1356665"),
                            Name = "Greece",
                            RegionCode = "GRC"
                        },
                        new
                        {
                            Id = new Guid("f5977133-5aa0-429b-b775-2ae8a300bdd7"),
                            Name = "Greenland",
                            RegionCode = "GRL"
                        },
                        new
                        {
                            Id = new Guid("2286efda-f9a8-413c-b20b-86423d37b0ea"),
                            Name = "Grenada",
                            RegionCode = "GRD"
                        },
                        new
                        {
                            Id = new Guid("607494b8-629e-4631-be41-7ba73075d15a"),
                            Name = "Guadeloupe",
                            RegionCode = "GLP"
                        },
                        new
                        {
                            Id = new Guid("30c63016-7050-4004-9517-828e82b251f2"),
                            Name = "Guam",
                            RegionCode = "GUM"
                        },
                        new
                        {
                            Id = new Guid("551a2d52-f553-44ea-ba18-ee8950c7f4d5"),
                            Name = "Guatemala",
                            RegionCode = "GTM"
                        },
                        new
                        {
                            Id = new Guid("16688199-f2e4-40e3-89f7-4cb44eb49435"),
                            Name = "Guinea",
                            RegionCode = "GIN"
                        },
                        new
                        {
                            Id = new Guid("83ac82f6-ca09-46fb-a821-cc1784d323f1"),
                            Name = "Guinea-Bissau",
                            RegionCode = "GNB"
                        },
                        new
                        {
                            Id = new Guid("ae5e0e81-1f98-402e-9d08-e7e06b2a9649"),
                            Name = "Guyana",
                            RegionCode = "GUY"
                        },
                        new
                        {
                            Id = new Guid("1ef147ef-5f54-413d-b2c7-241c1193870d"),
                            Name = "Haiti",
                            RegionCode = "HTI"
                        },
                        new
                        {
                            Id = new Guid("e996c821-907d-488b-a1df-e7d8c340f960"),
                            Name = "Honduras",
                            RegionCode = "HND"
                        },
                        new
                        {
                            Id = new Guid("126d4542-a972-40c5-8e9b-4d12ee1f0913"),
                            Name = "Hong Kong",
                            RegionCode = "HKG"
                        },
                        new
                        {
                            Id = new Guid("48a13235-44f0-4f56-92ae-fce4aa83bb58"),
                            Name = "Hungary",
                            RegionCode = "HUN"
                        },
                        new
                        {
                            Id = new Guid("0a693cbc-65f5-4ffb-8922-b0a55553a38d"),
                            Name = "Iceland",
                            RegionCode = "ISL"
                        },
                        new
                        {
                            Id = new Guid("c28548b5-729a-4ebc-83bf-ec6984d63239"),
                            Name = "India",
                            RegionCode = "IND"
                        },
                        new
                        {
                            Id = new Guid("388c899b-0d72-47b0-8dff-bbdcd4f46802"),
                            Name = "Indonesia",
                            RegionCode = "IDN"
                        },
                        new
                        {
                            Id = new Guid("e06bea91-ad9d-462a-be55-410494666022"),
                            Name = "Iran",
                            RegionCode = "IRN"
                        },
                        new
                        {
                            Id = new Guid("1072344e-805b-4f1f-93f6-5af5b0c8031b"),
                            Name = "Iraq",
                            RegionCode = "IRQ"
                        },
                        new
                        {
                            Id = new Guid("a2088b83-ff3a-49b2-ae8b-911e89c958bc"),
                            Name = "Ireland",
                            RegionCode = "IRL"
                        },
                        new
                        {
                            Id = new Guid("946d06ad-1895-4da4-8905-7a9fae77c9df"),
                            Name = "Israel",
                            RegionCode = "ISR"
                        },
                        new
                        {
                            Id = new Guid("6b7ba4c5-c0ee-4833-8190-d99d298a680d"),
                            Name = "Italy",
                            RegionCode = "ITA"
                        },
                        new
                        {
                            Id = new Guid("f9466109-d0df-4f62-a2c3-9cd59beff7ab"),
                            Name = "Jamaica",
                            RegionCode = "JAM"
                        },
                        new
                        {
                            Id = new Guid("52aacdb4-7b87-4083-bd8c-c3b790069518"),
                            Name = "Japan",
                            RegionCode = "JPN"
                        },
                        new
                        {
                            Id = new Guid("f545f055-1362-44d4-817a-5cc192b46779"),
                            Name = "Jordan",
                            RegionCode = "JOR"
                        },
                        new
                        {
                            Id = new Guid("9d833226-370e-473a-89c6-c0f60102079e"),
                            Name = "Kazakhstan",
                            RegionCode = "KAZ"
                        },
                        new
                        {
                            Id = new Guid("7c168d82-7141-4842-8619-c37ca0f6e391"),
                            Name = "Kenya",
                            RegionCode = "KEN"
                        },
                        new
                        {
                            Id = new Guid("3c180902-a6ad-4a71-8ae0-54f061c4d8c8"),
                            Name = "Kiribati",
                            RegionCode = "KIR"
                        },
                        new
                        {
                            Id = new Guid("cbbd86e4-e97e-46d8-a77d-6e8c59735139"),
                            Name = "Kuwait",
                            RegionCode = "KWT"
                        },
                        new
                        {
                            Id = new Guid("1ba40b1a-3875-4d58-8659-8bcbea3cbaf6"),
                            Name = "Kyrgyzstan",
                            RegionCode = "KGZ"
                        },
                        new
                        {
                            Id = new Guid("368a872d-7673-430e-8c61-23473abeb488"),
                            Name = "Laos",
                            RegionCode = "LAO"
                        },
                        new
                        {
                            Id = new Guid("cc0574c2-2b77-4021-833b-591725bd5522"),
                            Name = "Latvia",
                            RegionCode = "LVA"
                        },
                        new
                        {
                            Id = new Guid("690a7a9c-cc32-4114-bb33-3f40c0a0c46d"),
                            Name = "Lebanon",
                            RegionCode = "LBN"
                        },
                        new
                        {
                            Id = new Guid("e7fa5cfc-4edd-4bfc-a260-0472fb5fb6cd"),
                            Name = "Lesotho",
                            RegionCode = "LSO"
                        },
                        new
                        {
                            Id = new Guid("e8091d31-eb72-49ae-8fee-cd6f18fda83c"),
                            Name = "Liberia",
                            RegionCode = "LBR"
                        },
                        new
                        {
                            Id = new Guid("bdf6d028-c631-4173-b49f-2172a6931e64"),
                            Name = "Libya",
                            RegionCode = "LBY"
                        },
                        new
                        {
                            Id = new Guid("5e30a0fd-ffd1-4622-9bd4-01cf0ed7375c"),
                            Name = "Liechtenstein",
                            RegionCode = "LIE"
                        },
                        new
                        {
                            Id = new Guid("eac40c7d-f66b-4b2f-9c11-ea3f07653d39"),
                            Name = "Lithuania",
                            RegionCode = "LTU"
                        },
                        new
                        {
                            Id = new Guid("7ca749a2-ca96-4d56-b1bc-00add6a62812"),
                            Name = "Luxembourg",
                            RegionCode = "LUX"
                        },
                        new
                        {
                            Id = new Guid("c0e66abb-31dd-4549-be00-3db15cba0757"),
                            Name = "Macao",
                            RegionCode = "MAC"
                        },
                        new
                        {
                            Id = new Guid("41a14971-09fd-417d-b535-d2acd3b950de"),
                            Name = "Macedonia",
                            RegionCode = "MKD"
                        },
                        new
                        {
                            Id = new Guid("2b332487-53c8-4ab0-b307-d622251863a5"),
                            Name = "Madagascar",
                            RegionCode = "MDG"
                        },
                        new
                        {
                            Id = new Guid("4fc48814-f89d-40cd-a519-49096de71c5b"),
                            Name = "Malawi",
                            RegionCode = "MWI"
                        },
                        new
                        {
                            Id = new Guid("e897607d-caa5-4600-a730-a1773ddf78dc"),
                            Name = "Malaysia",
                            RegionCode = "MYS"
                        },
                        new
                        {
                            Id = new Guid("70a4a353-bcb2-4d81-bd0c-de61fb02d2d2"),
                            Name = "Maldives",
                            RegionCode = "MDV"
                        },
                        new
                        {
                            Id = new Guid("2069296b-5a6f-4307-a024-4718046969e9"),
                            Name = "Mali",
                            RegionCode = "MLI"
                        },
                        new
                        {
                            Id = new Guid("86704fa4-1a45-4edf-9f9a-cb514b323c26"),
                            Name = "Malta",
                            RegionCode = "MLT"
                        },
                        new
                        {
                            Id = new Guid("d671ea5a-5ca5-4627-911a-02ab5d2720f7"),
                            Name = "Marshall Islands",
                            RegionCode = "MHL"
                        },
                        new
                        {
                            Id = new Guid("4da76031-86b0-4ca6-ba4c-9e5264ec28bb"),
                            Name = "Martinique",
                            RegionCode = "MTQ"
                        },
                        new
                        {
                            Id = new Guid("4ff9d14f-973a-48c8-b468-ff2b9360f85a"),
                            Name = "Mauritania",
                            RegionCode = "MRT"
                        },
                        new
                        {
                            Id = new Guid("cbc0780c-1c7c-4385-92a3-cac700e9383e"),
                            Name = "Mauritius",
                            RegionCode = "MUS"
                        },
                        new
                        {
                            Id = new Guid("0689e7db-1c26-4927-a6e5-9060c5e37ef6"),
                            Name = "Mayotte",
                            RegionCode = "MYT"
                        },
                        new
                        {
                            Id = new Guid("3beff3ec-d592-4e64-8141-ede0d7926d9d"),
                            Name = "Mexico",
                            RegionCode = "MEX"
                        },
                        new
                        {
                            Id = new Guid("69114e5e-5291-490c-9546-86f7f7db5ed9"),
                            Name = "Moldova",
                            RegionCode = "MDA"
                        },
                        new
                        {
                            Id = new Guid("75cd247e-7a92-407d-ab02-ea555db956f5"),
                            Name = "Monaco",
                            RegionCode = "MCO"
                        },
                        new
                        {
                            Id = new Guid("f224e513-82d1-4b02-ad14-da99c58dec5f"),
                            Name = "Mongolia",
                            RegionCode = "MNG"
                        },
                        new
                        {
                            Id = new Guid("ff5afbf0-bc33-456b-8c6e-b4eb10e1974a"),
                            Name = "Montenegro",
                            RegionCode = "MNE"
                        },
                        new
                        {
                            Id = new Guid("816ff37c-39bd-433d-93b9-7380426e0a80"),
                            Name = "Montserrat",
                            RegionCode = "MSR"
                        },
                        new
                        {
                            Id = new Guid("402fabc6-831c-40c0-8b6e-97a92a6cfca2"),
                            Name = "Morocco",
                            RegionCode = "MAR"
                        },
                        new
                        {
                            Id = new Guid("95f64d39-97f3-4437-b8bd-808131d6a378"),
                            Name = "Mozambique",
                            RegionCode = "MOZ"
                        },
                        new
                        {
                            Id = new Guid("a03d69c5-f1c2-4961-a5a3-dc66d87e2e8a"),
                            Name = "Namibia",
                            RegionCode = "NAM"
                        },
                        new
                        {
                            Id = new Guid("a8b8698e-6aa3-46a6-a936-56165fe06453"),
                            Name = "Nauru",
                            RegionCode = "NRU"
                        },
                        new
                        {
                            Id = new Guid("576495e5-df84-425a-b7fc-c395dc469059"),
                            Name = "Nepal",
                            RegionCode = "NPL"
                        },
                        new
                        {
                            Id = new Guid("ea477cc6-2983-42d8-a640-2f82ed16bbb5"),
                            Name = "Netherlands",
                            RegionCode = "NLD"
                        },
                        new
                        {
                            Id = new Guid("27fe9e3e-59e7-4148-bf6a-642b59d308fc"),
                            Name = "Netherlands Antilles",
                            RegionCode = "ANT"
                        },
                        new
                        {
                            Id = new Guid("9b7e6263-ae2f-48fd-85d4-e964330c8bc3"),
                            Name = "New Caledonia",
                            RegionCode = "NCL"
                        },
                        new
                        {
                            Id = new Guid("2e008a42-65b9-476b-b2b8-29c2ebfeac02"),
                            Name = "New Zealand",
                            RegionCode = "NZL"
                        },
                        new
                        {
                            Id = new Guid("46f576b8-043f-4d97-b0c4-ac70c2307509"),
                            Name = "Nicaragua",
                            RegionCode = "NIC"
                        },
                        new
                        {
                            Id = new Guid("f95cb30f-05b0-415f-a490-028ecd7287c6"),
                            Name = "Niger",
                            RegionCode = "NER"
                        },
                        new
                        {
                            Id = new Guid("a84fd59a-a34c-4fd7-a732-ced62b636a79"),
                            Name = "Nigeria",
                            RegionCode = "NGA"
                        },
                        new
                        {
                            Id = new Guid("4c0f1804-5aab-4513-ae68-7555288727c7"),
                            Name = "Niue",
                            RegionCode = "NIU"
                        },
                        new
                        {
                            Id = new Guid("b514cd7f-e8c2-47f6-8a53-15e898d448d5"),
                            Name = "Norfolk Island",
                            RegionCode = "NFK"
                        },
                        new
                        {
                            Id = new Guid("a3e73fff-c491-4401-91b3-ee10ac7c73c5"),
                            Name = "North Korea",
                            RegionCode = "PRK"
                        },
                        new
                        {
                            Id = new Guid("b38c12f6-5075-4d63-b59c-01f5a82ee604"),
                            Name = "Northern Mariana Islands",
                            RegionCode = "MNP"
                        },
                        new
                        {
                            Id = new Guid("4a2ae710-a1fa-47da-8567-9619ead35007"),
                            Name = "Norway",
                            RegionCode = "NOR"
                        },
                        new
                        {
                            Id = new Guid("97426f38-ce9c-40cc-91bc-056a1b5e1c33"),
                            Name = "Oman",
                            RegionCode = "OMN"
                        },
                        new
                        {
                            Id = new Guid("fb062b0b-b5a2-4437-998c-fd971b259987"),
                            Name = "Pakistan",
                            RegionCode = "PAK"
                        },
                        new
                        {
                            Id = new Guid("8c74c902-3932-40b7-9fa6-829aade592a8"),
                            Name = "Palau",
                            RegionCode = "PLW"
                        },
                        new
                        {
                            Id = new Guid("36112f03-36b2-49fe-95cf-827a52d388e3"),
                            Name = "Palestine",
                            RegionCode = "PSE"
                        },
                        new
                        {
                            Id = new Guid("068034d9-9cde-42c6-bba1-d98e13863c07"),
                            Name = "Panama",
                            RegionCode = "PAN"
                        },
                        new
                        {
                            Id = new Guid("e25b0975-cdc1-4400-ad43-d23192cba24a"),
                            Name = "Papua New Guinea",
                            RegionCode = "PNG"
                        },
                        new
                        {
                            Id = new Guid("9df7c8b7-9598-4260-b8f0-f60fa662f71d"),
                            Name = "Paraguay",
                            RegionCode = "PRY"
                        },
                        new
                        {
                            Id = new Guid("d9597381-99fe-4e76-8851-a7a1eba3162d"),
                            Name = "Peru",
                            RegionCode = "PER"
                        },
                        new
                        {
                            Id = new Guid("9635e7f0-0487-4f9d-935b-eb9cdd50837c"),
                            Name = "Philippines",
                            RegionCode = "PHL"
                        },
                        new
                        {
                            Id = new Guid("06180615-62b8-4c31-8df9-bea774b097c2"),
                            Name = "Poland",
                            RegionCode = "POL"
                        },
                        new
                        {
                            Id = new Guid("98e2972e-fd62-451f-8644-02b3583d486e"),
                            Name = "Portugal",
                            RegionCode = "PRT"
                        },
                        new
                        {
                            Id = new Guid("7aa21b5a-1c8f-498b-8894-fc1b8c8a377a"),
                            Name = "Puerto Rico",
                            RegionCode = "PRI"
                        },
                        new
                        {
                            Id = new Guid("a0b98187-d853-410b-9912-e2696003a64c"),
                            Name = "Qatar",
                            RegionCode = "QAT"
                        },
                        new
                        {
                            Id = new Guid("fecca425-4190-4f5b-a3f9-0879763c827f"),
                            Name = "Congo",
                            RegionCode = "COG"
                        },
                        new
                        {
                            Id = new Guid("b920afb8-8877-4c92-939d-29e3dcc1e65a"),
                            Name = "Réunion",
                            RegionCode = "REU"
                        },
                        new
                        {
                            Id = new Guid("96a85540-a5b7-450c-9142-81c1789a75f3"),
                            Name = "Romania",
                            RegionCode = "ROU"
                        },
                        new
                        {
                            Id = new Guid("9238d4ce-b50e-4b39-be5d-04b6eac94689"),
                            Name = "Russia",
                            RegionCode = "RUS"
                        },
                        new
                        {
                            Id = new Guid("733eefe1-8824-467e-8b0d-e840668c1aa2"),
                            Name = "Rwanda",
                            RegionCode = "RWA"
                        },
                        new
                        {
                            Id = new Guid("00ee0ba9-7e01-42a2-8256-233d7883bc69"),
                            Name = "Saint Barthélemy",
                            RegionCode = "BLM"
                        },
                        new
                        {
                            Id = new Guid("e279ee55-ef69-46b6-85d8-8498134ff5ad"),
                            Name = "Saint Helena",
                            RegionCode = "SHN"
                        },
                        new
                        {
                            Id = new Guid("4f43e434-d5d5-45ff-8823-36359794b37f"),
                            Name = "Saint Kitts and Nevis",
                            RegionCode = "KNA"
                        },
                        new
                        {
                            Id = new Guid("2b9d2a06-fec2-4835-b3cf-018315c5de95"),
                            Name = "Saint Martin",
                            RegionCode = "MAF"
                        },
                        new
                        {
                            Id = new Guid("b31f8b76-418b-4281-a69d-58aaa91f6f6a"),
                            Name = "Saint Pierre and Miquelon",
                            RegionCode = "SPM"
                        },
                        new
                        {
                            Id = new Guid("ea999b03-3dd8-4c27-a1cd-c2e3871f50c0"),
                            Name = "Saint Vincent and the Grenadines",
                            RegionCode = "VCT"
                        },
                        new
                        {
                            Id = new Guid("02c0dc8d-b263-4660-b732-2265c5d13e69"),
                            Name = "Samoa",
                            RegionCode = "WSM"
                        },
                        new
                        {
                            Id = new Guid("56e024f5-cc64-4a98-8d34-f93e36106e85"),
                            Name = "San Marino",
                            RegionCode = "SMR"
                        },
                        new
                        {
                            Id = new Guid("64a6c93a-6a8c-4177-b64f-8f64742f787d"),
                            Name = "São Tomé and Príncipe",
                            RegionCode = "STP"
                        },
                        new
                        {
                            Id = new Guid("575644b9-32a0-4ad1-84a9-75187199fcbf"),
                            Name = "Saudi Arabia",
                            RegionCode = "SAU"
                        },
                        new
                        {
                            Id = new Guid("ed595310-bbfd-45a8-80df-8f3b6ee18796"),
                            Name = "Senegal",
                            RegionCode = "SEN"
                        },
                        new
                        {
                            Id = new Guid("6ef6c0df-a021-4502-9ff9-0e96b78804da"),
                            Name = "Serbia",
                            RegionCode = "SRB"
                        },
                        new
                        {
                            Id = new Guid("fa4eb665-9b96-4889-9794-1481efaed2e3"),
                            Name = "Seychelles",
                            RegionCode = "SYC"
                        },
                        new
                        {
                            Id = new Guid("2e4c64a4-bff6-4397-a981-5238ca8aa427"),
                            Name = "Sierra Leone",
                            RegionCode = "SLE"
                        },
                        new
                        {
                            Id = new Guid("55c659d0-759f-41df-af18-d6c5838c9d42"),
                            Name = "Singapore",
                            RegionCode = "SGP"
                        },
                        new
                        {
                            Id = new Guid("ac601f9a-7f48-4305-a1b4-9ef5f295cd88"),
                            Name = "Sint Maarten (Dutch part)",
                            RegionCode = "SXM"
                        },
                        new
                        {
                            Id = new Guid("7b8fe5ae-b4f8-4559-a6c8-7af8aaf8a4ec"),
                            Name = "Slovakia",
                            RegionCode = "SVK"
                        },
                        new
                        {
                            Id = new Guid("1576d87b-ef8f-48a9-884b-e8e7e03fca3e"),
                            Name = "Slovenia",
                            RegionCode = "SVN"
                        },
                        new
                        {
                            Id = new Guid("f22051e1-43b2-44d7-9ac2-3bb84a40f0d1"),
                            Name = "Solomon Islands",
                            RegionCode = "SLB"
                        },
                        new
                        {
                            Id = new Guid("12e42f7d-3246-4478-8183-e981b213af83"),
                            Name = "Somalia",
                            RegionCode = "SOM"
                        },
                        new
                        {
                            Id = new Guid("c6094038-756a-4f14-bb19-cb8064430e19"),
                            Name = "South Africa",
                            RegionCode = "ZAF"
                        },
                        new
                        {
                            Id = new Guid("1c582cb7-f8f7-4f48-9f1b-f10e8f340c14"),
                            Name = "South Korea",
                            RegionCode = "KOR"
                        },
                        new
                        {
                            Id = new Guid("7ace4da6-d415-425c-8648-565e9e6f37db"),
                            Name = "South Sudan",
                            RegionCode = "SSD"
                        },
                        new
                        {
                            Id = new Guid("c4724071-5e46-41be-876f-1e82b5c03cfc"),
                            Name = "Spain",
                            RegionCode = "ESP"
                        },
                        new
                        {
                            Id = new Guid("5caa4073-6545-4fbc-adc1-4f0fe49e1366"),
                            Name = "Sri Lanka",
                            RegionCode = "LKA"
                        },
                        new
                        {
                            Id = new Guid("3ff57e57-2cd0-44b9-9ebc-7eb7f81ce721"),
                            Name = "Saint Lucia",
                            RegionCode = "LCA"
                        },
                        new
                        {
                            Id = new Guid("66095e2c-b4fc-4b7f-83f8-ad4cc779713e"),
                            Name = "Sudan",
                            RegionCode = "SDN"
                        },
                        new
                        {
                            Id = new Guid("04b4af98-a797-430b-807d-2eb5e2e72ef9"),
                            Name = "Suriname",
                            RegionCode = "SUR"
                        },
                        new
                        {
                            Id = new Guid("3cc9ccd0-de2c-416b-8ffb-5afc1b474eb1"),
                            Name = "Swaziland",
                            RegionCode = "SWZ"
                        },
                        new
                        {
                            Id = new Guid("af7d6acf-4ef8-47c4-b0b9-158a3026568f"),
                            Name = "Sweden",
                            RegionCode = "SWE"
                        },
                        new
                        {
                            Id = new Guid("47e14ca6-b241-4adb-9228-ac7c69ae72a0"),
                            Name = "Switzerland",
                            RegionCode = "CHE"
                        },
                        new
                        {
                            Id = new Guid("70767f56-e268-4631-bdda-312852df1391"),
                            Name = "Syrian Arab Republic",
                            RegionCode = "SYR"
                        },
                        new
                        {
                            Id = new Guid("d3c5afc6-3b04-4151-9e09-df55e9925a8c"),
                            Name = "Taiwan",
                            RegionCode = "TWN"
                        },
                        new
                        {
                            Id = new Guid("2b2ffa09-0a22-41d0-a5b3-480ecef730f8"),
                            Name = "Tajikistan",
                            RegionCode = "TJK"
                        },
                        new
                        {
                            Id = new Guid("f336f2ba-cd3f-4acd-a487-176e3d52f861"),
                            Name = "Tanzania",
                            RegionCode = "TZA"
                        },
                        new
                        {
                            Id = new Guid("289fc561-290d-475e-9955-0c443b7eca28"),
                            Name = "Thailand",
                            RegionCode = "THA"
                        },
                        new
                        {
                            Id = new Guid("9ff96a93-405c-4c4a-b350-9142b54798ba"),
                            Name = "Bahamas",
                            RegionCode = "BHS"
                        },
                        new
                        {
                            Id = new Guid("42955299-cef4-4bf9-b6cd-d790c7aa32e6"),
                            Name = "Gambia",
                            RegionCode = "GMB"
                        },
                        new
                        {
                            Id = new Guid("7692fd4b-3ca2-42f0-b48c-9b5f1772d83b"),
                            Name = "Timor-Leste",
                            RegionCode = "TLS"
                        },
                        new
                        {
                            Id = new Guid("18cc6fbb-9901-4323-8395-a91255a327db"),
                            Name = "Togo",
                            RegionCode = "TGO"
                        },
                        new
                        {
                            Id = new Guid("8182fe27-e767-4a6f-9953-4e79830f53aa"),
                            Name = "Tokelau",
                            RegionCode = "TKL"
                        },
                        new
                        {
                            Id = new Guid("e3c1979a-91fa-4ba0-a463-f9020fa62107"),
                            Name = "Tonga",
                            RegionCode = "TON"
                        },
                        new
                        {
                            Id = new Guid("3d341b6b-393d-4685-80cf-df2b90f76c9b"),
                            Name = "Trinidad and Tobago",
                            RegionCode = "TTO"
                        },
                        new
                        {
                            Id = new Guid("8dc81940-df37-4300-b831-d6748ca5b006"),
                            Name = "Tunisia",
                            RegionCode = "TUN"
                        },
                        new
                        {
                            Id = new Guid("d87f4c8c-7c76-4c8d-9c2e-0369aaa95dca"),
                            Name = "Turkey",
                            RegionCode = "TUR"
                        },
                        new
                        {
                            Id = new Guid("4017a8a5-4009-4c60-a8e5-9008ee143e78"),
                            Name = "Turkmenistan",
                            RegionCode = "TKM"
                        },
                        new
                        {
                            Id = new Guid("cb613895-5d9b-4d63-a3e0-8126fcddbb73"),
                            Name = "Turks and Caicos Islands",
                            RegionCode = "TCA"
                        },
                        new
                        {
                            Id = new Guid("7a8ebb2b-3ff4-4ea1-b3a9-34f8beffee17"),
                            Name = "Tuvalu",
                            RegionCode = "TUV"
                        },
                        new
                        {
                            Id = new Guid("0fc1434b-7bda-4dc6-8113-9d3e964dd1ba"),
                            Name = "Uganda",
                            RegionCode = "UGA"
                        },
                        new
                        {
                            Id = new Guid("50fbfe12-6996-41c7-a80b-1dc68cca64c3"),
                            Name = "Ukraine",
                            RegionCode = "UKR"
                        },
                        new
                        {
                            Id = new Guid("9dead4d9-c580-4671-9274-f7c914bfc69f"),
                            Name = "United Arab Emirates",
                            RegionCode = "ARE"
                        },
                        new
                        {
                            Id = new Guid("04c34188-2795-4261-9a3a-cc438d4dc077"),
                            Name = "United Kingdom",
                            RegionCode = "GBR"
                        },
                        new
                        {
                            Id = new Guid("22920a80-a37c-4c6d-9f4a-4987f19f01cb"),
                            Name = "United States",
                            RegionCode = "USA"
                        },
                        new
                        {
                            Id = new Guid("72cbd740-c660-4bfd-b330-752e85e13336"),
                            Name = "Uruguay",
                            RegionCode = "URY"
                        },
                        new
                        {
                            Id = new Guid("3ab696b0-aee2-4719-8bf4-27d82dd21add"),
                            Name = "U.S. Virgin Islands",
                            RegionCode = "VIR"
                        },
                        new
                        {
                            Id = new Guid("a774386a-7a4c-4a96-9e68-b314eb43f071"),
                            Name = "Uzbekistan",
                            RegionCode = "UZB"
                        },
                        new
                        {
                            Id = new Guid("7ef2f495-062a-41f3-8656-55a6fce77d5e"),
                            Name = "Vanuatu",
                            RegionCode = "VUT"
                        },
                        new
                        {
                            Id = new Guid("08291284-85a1-4b7b-a5cf-ca2b66a40492"),
                            Name = "Vatican City",
                            RegionCode = "VAT"
                        },
                        new
                        {
                            Id = new Guid("b20a48df-b3ee-4381-82d5-99fd0a2f86f6"),
                            Name = "Venezuela",
                            RegionCode = "VEN"
                        },
                        new
                        {
                            Id = new Guid("7259f1ea-8276-4148-8fb2-9c184d5e8fce"),
                            Name = "Vietnam",
                            RegionCode = "VNM"
                        },
                        new
                        {
                            Id = new Guid("94f11506-8574-40b4-8527-150726421558"),
                            Name = "Wallis and Futuna",
                            RegionCode = "WLF"
                        },
                        new
                        {
                            Id = new Guid("6de2322d-4fee-46c8-9e32-0afda7b72764"),
                            Name = "Yemen",
                            RegionCode = "YEM"
                        },
                        new
                        {
                            Id = new Guid("a641bc11-0727-42f1-a643-bcc871d19dc5"),
                            Name = "Zambia",
                            RegionCode = "ZMB"
                        },
                        new
                        {
                            Id = new Guid("ab4ef8a3-6be2-4d47-a6c4-22ab63cbfac2"),
                            Name = "Zimbabwe",
                            RegionCode = "ZWE"
                        });
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleEnum")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.RoleClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Security.SecurityCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("CodeActionType")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SecurityCodes");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("XrefUserRole");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Comment", b =>
                {
                    b.HasOne("AspNetCoreSpa.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId");

                    b.HasOne("AspNetCoreSpa.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Image", b =>
                {
                    b.HasOne("AspNetCoreSpa.Domain.Entities.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId");

                    b.HasOne("AspNetCoreSpa.Domain.Entities.User", "User")
                        .WithOne("Image")
                        .HasForeignKey("AspNetCoreSpa.Domain.Entities.Image", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Like", b =>
                {
                    b.HasOne("AspNetCoreSpa.Domain.Entities.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId");

                    b.HasOne("AspNetCoreSpa.Domain.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId");

                    b.HasOne("AspNetCoreSpa.Domain.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.Post", b =>
                {
                    b.HasOne("AspNetCoreSpa.Domain.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.RoleClaim", b =>
                {
                    b.HasOne("AspNetCoreSpa.Domain.Entities.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.User", b =>
                {
                    b.HasOne("AspNetCoreSpa.Domain.Entities.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("AspNetCoreSpa.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("AspNetCoreSpa.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreSpa.Domain.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
